version: "3.7"

services:
  db:
    container_name: postgres
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
        - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - twitch-backend

  redis:
    container_name: redis
    image: redis:5.0
    restart: always
    ports:
        - "6379:6379"
    command:
      - redis-server --requirepass ${REDIS_PASSWORD} # requiring password for redis on start
    volumes:
      - redis_data:/data
    networks:
      twitch-backend:

volumes:
    postgres-data:
    redis_data:

networks:
  twitch-backend: