version: "3.7"

services:
  db:
    container_name: postgres
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
        - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - twitch-backend


volumes:
    postgres-data:

networks:
  twitch-backend: